// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJUa0RHcsCE8W24JQYi1lNlbVEG-5NJaI',
    appId: '1:1061120194163:web:70f4fe17dbd930fcad1c06',
    messagingSenderId: '1061120194163',
    projectId: 'share-leaks',
    authDomain: 'share-leaks.firebaseapp.com',
    databaseURL: 'https://share-leaks-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'share-leaks.appspot.com',
    measurementId: 'G-NB7B4RMXQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtptWaKnGcunTHtjXJf3o4eeX6SMIT38w',
    appId: '1:1061120194163:android:daa002b903823b2ead1c06',
    messagingSenderId: '1061120194163',
    projectId: 'share-leaks',
    databaseURL: 'https://share-leaks-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'share-leaks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIXclVsIJw-o_76OmJFZ5kKCIPPCsPKqg',
    appId: '1:1061120194163:ios:14c752fda4adab4dad1c06',
    messagingSenderId: '1061120194163',
    projectId: 'share-leaks',
    databaseURL: 'https://share-leaks-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'share-leaks.appspot.com',
    iosClientId: '1061120194163-d063klj5br8u9l9s3dvddd3a00c17ard.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareleaks',
  );
}
